### ISSUE TITLE
Broken link in Style Guide and Conventions

### ISSUE THREAD

**Issue by sandipanpanda** [google/pigweed#1]
Broken link in line 27 of Style Guide and Conventions [Style Guide and Conventions](https://github.com/sandipanpanda/pigweed/blob/main/docs/style_guide.rst)

`line 27:` Recommendations in the :doc:`embedded_cpp_guide` are considered part of the

**Comment by 255** [comment]
Hi @sandipanpanda,
Thank for you filing this issue. The link you refer to does not work on GitHub, but it does work correctly on our website (https://pigweed.dev/docs/style_guide.html).

We use Sphinx and reStructuredText for our documentation. GitHub attempts to display our documentation, but it doesn't have a full understanding of reST/Sphinx so it can't display some elements correctly. To view the docs, please visit https://pigweed.dev.

We plan to add README.md files to the repo that point to our website. Hopefully that will make it easier to find the rendered docs.

Thanks!
