### ISSUE TITLE
Venv patterns without deactivate

### ISSUE THREAD

**Issue by FrenchBen** [google/pigweed#3]
Pigweed seems to mimic the venv module that Python offers, yet doesn't document how to exit an activated environment.

Typical python pattern:
```
$ source bin/activate
python-venv ❯ deactivate
$
```
https://docs.python.org/3/library/venv.html
>You can deactivate a virtual environment by typing “deactivate” in your shell. The exact mechanism is platform-specific and is an internal implementation detail (typically a script or shell function will be used).

Typical pigweed pattern:
```
$ source scripts/activate.sh
pigweed-venv ❯ deactivate
zsh: command not found: deactivate
```
https://pigweed.dev/pw_env_setup/
>At this time `pw_env_setup` works for us, but isn’t well tested. We don’t suggest relying on it just yet. However, we are interested in experience reports;

**Comment by FrenchBen** [comment]
> Hello, Thanks for filing this issue!
> 
> After you've activated a Pigweed environment, you can deactivate it with the `pw_deactivate` command. It appears that this is not documented; we'll fix that.

any reason the command isn't the common `deactivate`, making it easier to transfer python-like patterns to Pigweed?

**Comment by mohrr** [comment]
`pw_deactivate` is meant to be used internally and actually leaves a couple variables set. I'm creating a new `deactivate` shell function with https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/68080.

**Comment by FrenchBen** [comment]
Thank you for adding this! 🌮 🌮 🌮
